export const GET_TODOS_FETCHING = 'GET_TODOS_FETCHING';
export const GET_TODOS_RECEIEVED = 'GET_TODOS_RECEIEVED';
export const GET_TODOS_FAILED = 'GET_TODOS_FAILED';

export const DELETE_TODOS = 'DELETE_TODOS';